### PR TITLE
📈Order by relationship

### PR DESCRIPTION
**Pull request by rovansteen**
This is a first draft of trying to order by relationship. This definitely needs some more tests as we need to join the relationship to be able to sort on it. So this might not work for every relation type. 

This is also a breaking change because the API for ordering will change. A welcome side effect is that it allows us to filter on multiple columns and relations.

@erikgaal what do you think?

### CODE REVIEW

**Comment by erikgaal** [comment]
Looks good, I really like the structure of the `Order` input types.

**Comment by rovansteen** [comment]
Yeah. What kind of situations do you think the join won’t work? Pivot and polymorphic relations. What else?

And we might want to test if the join doesn’t interfere with the data via eloquent in some way.

**Comment by rovansteen** [comment]
Since #25 shipped a proper join relationship, we can continue implementing this!

**Comment by rovansteen** [comment]
@erikgaal can you approve this PR?

**Pull request merged**
